setup:
    selenium:
        chrome_driver:
            url: https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
        firefox_driver:
            url: https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
            binary_name: geckodriver
    ospdui:
        repo: git://git.app.eng.bos.redhat.com/ospdui.git
        revision: OLD_OSP
        dir: ~/ospdui_tests
    network:
        dev: eth0
        ipaddr: 192.168.24.240
        netmask: 255.255.255.0
